name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the code
      uses: actions/checkout@v3

    - name: Automatic Tag increase
      id: increment-git-tag
      run: |
        bash ./github-build/tag_update.sh -v patch

    - name: install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: latest

    - name: Update kube config
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_CI_USERNAME }}
        password: ${{ secrets.DOCKERHUB_CI_PASSWORD }}
      
    - name: Build the Docker image
      id: build-image
      env:
        REGISTRY: objectiveit
        IMAGE: insurances-online
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}

      run: |
        docker build . -f ./Dockerfile.app -t $REGISTRY/$IMAGE-app:$IMAGE_TAG
        docker push $REGISTRY/$IMAGE-app:$IMAGE_TAG
        docker build . -f ./Dockerfile.server -t $REGISTRY/$IMAGE-srv:$IMAGE_TAG
        docker push $REGISTRY/$IMAGE-srv:$IMAGE_TAG

    - name: Deploy to test
      id: deploy-to-test
      env:
        #kubeconfig: ${{ secrets.KUBE_CONFIG }}
        NAMESPACE: insurances-online-qs
        DEPLOYMENT_NAME: insurances-online
        CONTAINER_NAME: insurances-online
        REGISTRY: objectiveit
        IMAGE: insurances-online
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}

      run: |
        # mkdir -p ~/.kube && echo $kubeconfig > ~/.kube/config
        kubectl -n $NAMESPACE set image deployment/$DEPLOYMENT_NAME-app $CONTAINER_NAME-app=$REGISTRY/$IMAGE-app:$IMAGE_TAG
        kubectl -n $NAMESPACE set image deployment/$DEPLOYMENT_NAME-srv $CONTAINER_NAME-srv=$REGISTRY/$IMAGE-srv:$IMAGE_TAG
